CREATE DATABASE SCHOOL;

USE SCHOOL;

CREATE TABLE
  IF NOT EXISTS PROF (
    PROF_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROF_FNAME VARCHAR(50) NOT NULL,
    PROF_LNAME VARCHAR(50) NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS STUDENT (
    STUD_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUD_FNAME VARCHAR(50) NOT NULL,
    STUD_LNAME VARCHAR(50) NOT NULL,
    STUD_STREET VARCHAR(255) NOT NULL,
    STUD_CITY VARCHAR(50) NOT NULL,
    STUD_ZIP VARCHAR(10) NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS COURSE (
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(255) NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS CLASS (
    CLASS_ID INT PRIMARY KEY,
    CLASS_NAME VARCHAR(255) NOT NULL,
    PROF_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    CONSTRAINT FK_PROFESSOR FOREIGN KEY (PROF_ID) REFERENCES PROF (PROF_ID),
    CONSTRAINT FK_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
  );

CREATE TABLE
  IF NOT EXISTS ROOM (
    ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_LOC VARCHAR(50) NOT NULL,
    ROOM_CAP VARCHAR(50) NOT NULL,
    CLASS_ID INT UNIQUE,
    CONSTRAINT FK_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS (CLASS_ID)
  );

CREATE TABLE
  IF NOT EXISTS ENROLL (
    STUD_ID INT,
    CLASS_ID INT,
    GRADE VARCHAR(3) NOT NULL,
    PRIMARY KEY (STUD_ID, CLASS_ID),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY (STUD_ID) REFERENCES STUDENT (STUD_ID),
    CONSTRAINT FK_ENROLL_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS (CLASS_ID)
  );